Repository paritytech/litep2p, pull requests merged in 2024-08, with the labels that each got.

#194 transport: Add accept_pending/reject_pending for inbound connections and introduce inbound limits
  src/transport/dummy.rs
  src/transport/manager/limits.rs
  src/transport/manager/mod.rs
  src/transport/mod.rs
  src/transport/quic/mod.rs
  src/transport/tcp/connection.rs
  src/transport/tcp/mod.rs
  src/transport/webrtc/mod.rs
  src/transport/websocket/mod.rs
Labels: enhancement

#198 Fix TCP, WebSocket, QUIC leaking connection IDs in `reject()`
  src/transport/quic/mod.rs
  src/transport/tcp/mod.rs
  src/transport/websocket/mod.rs
Labels: bug

#213 kad: Handle `ADD_PROVIDER` & `GET_PROVIDERS` network requests
  src/protocol/libp2p/kademlia/config.rs
  src/protocol/libp2p/kademlia/message.rs
  src/protocol/libp2p/kademlia/mod.rs
  src/protocol/libp2p/kademlia/store.rs
  src/protocol/libp2p/schema/kademlia.proto
Labels: enhancement

#214 crypto/noise: Generate keypair only for Curve25519
  src/crypto/noise/protocol.rs
Labels: enhancement

#215 minor: fix tests without `websocket` feature
  src/transport/manager/mod.rs
Labels: bug, easy

#217 substream: Use write_all instead of manually writing bytes
  src/substream/mod.rs
Labels: enhancement

#223 transport: Replace trust_dns_resolver with hickory_resolver
  Cargo.lock
  Cargo.toml
  src/transport/common/listener.rs
Labels: enhancement

#222 kad: Fix substream opening and dialing race
  src/protocol/libp2p/kademlia/mod.rs
  src/protocol/libp2p/kademlia/query/find_node.rs
Labels: bug
